# Generated by Django 3.0.7 on 2020-06-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='image')),
                ('comment', models.TextField(default='간단한 설명')),
            ],
        ),
        migrations.RemoveField(
            model_name='archiving',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='archiving',
            name='photo',
        ),
    ]
