# Generated by Django 3.0.7 on 2020-06-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailyApp', '0002_auto_20200625_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='archiving',
        ),
    ]
